version: '3.9'
services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: food-delivery
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

